name: Build Test image
on:
  workflow_dispatch:
    inputs:
      shrink:
        description: 'shrink .img to img.xz?'
        type: boolean
        default: false
        required: true
      id:
        description: 'board id to make'
        type: string
        default: opi3b
        required: true
      name:
        description: 'friendly name'
        type: string
        default: User Defined Board ID
        required: true


jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: "${{ github.event.inputs.name }}" 
          id: "${{ github.event.inputs.id }}"  
        
    steps:
      - uses: actions/checkout@v4
        with:
          path: publish/build

      - name: Extract version from file
        id: get_version
        run: |
          VERSION=$(cut -d "'" -f2 < publish/build/pwnagotchi/_version.py)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install qemu dependencies
        run: sudo apt update && sudo apt install qemu-user-static qemu-utils xz-utils -y

      - name: Build ${{ matrix.name }} img file
        run: cd publish/build; ls -la .; pwd; make packer; make ${{ matrix.id }}
      
      - name: Change name of .img to add version
        run: |
          sudo chown runner:docker "pwnagotchi-${{ matrix.id }}.img"
          mv "pwnagotchi-${{ matrix.id }}.img" "pwnagotchi-${{ env.VERSION }}-${{ matrix.id }}-TestImage${{ env.GITHUB_RUN_NUMBER }}.img"

      - name: PiShrink
        if: ${{ github.event.inputs.shrink }} 
        run: |
          wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
          chmod +x pishrink.sh
          sudo mv pishrink.sh /usr/local/bin
          sudo pishrink.sh -aZ "pwnagotchi-${{ env.VERSION }}-${{ matrix.id }}-TestImage${{ env.GITHUB_RUN_NUMBER }}.img"

      - name: debug 
        if: failure()
        run: |
          echo ###############################################
          echo ${{ matrix.id }} build failed, listing files
          echo ###############################################
          ls -lR ${{ env.GITHUB_WORKSPACE }}
          echo ###############################################
          echo disk usage
          echo ###############################################
          sudo df -h
      
      - name: Upload ${{ matrix.id }} image
        if: ${{ github.event.inputs.shrink }} 
        uses: actions/upload-artifact@v4
        with:
          name: Pwnagatchi-${{ matrix.id }}-TestImage-${{ env.GITHUB_RUN_NUMBER }}
          path: pwnagotchi-${{ env.VERSION }}-${{ matrix.id }}-TestImage${{ env.GITHUB_RUN_NUMBER }}.img.xz

      - name: Upload ${{ matrix.id }} image
        if: ${{ !(github.event.inputs.shrink) }} 
        uses: actions/upload-artifact@v4
        with:
          name: Pwnagatchi-${{ matrix.id }}-TestImage-${{ env.GITHUB_RUN_NUMBER }}
          path: pwnagotchi-${{ env.VERSION }}-${{ matrix.id }}-TestImage${{ env.GITHUB_RUN_NUMBER }}.img

      #- name: Release
      #  uses: softprops/action-gh-release@v2
      #  with:
      #    prerelease: false
      #    make_latest: true
      #    tag_name: v${{ env.VERSION }}
      #    name: Pwnagotchi v${{ env.VERSION }}
      #    files: pwnagotchi-${{ env.VERSION }}-${{ matrix.id }}-TestImage${{ env.GITHUB_RUN_NUMBER }}.img.xz
      #    generate_release_notes: true
